name: save_file_formats
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  file_picker: ^5.5.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/

  fonts:
    - family: Rubik-Light
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf

    - family: Rubik-SemiBold
      fonts:
        - asset: assets/fonts/Rubik-SemiBold.ttf  

    - family: Rubik-Bold
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf

